# Generated by Django 5.0.4 on 2024-05-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipayapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin_code',
            field=models.CharField(default='1234', max_length=4),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=10),
        ),
    ]
